
name : pr
on : [ pull_request ]

jobs :

  Cancel :
    name : 'Cancel Previous Runs'
    runs-on : ubuntu-latest
    timeout-minutes : 1
    steps :
      - uses : styfle/cancel-workflow-action@0.4.0
        with :
          access_token : ${{ github.token }}

  Fast :
    env :
      PRIVATE_WTOOLS_BOT_TOKEN : ${{ secrets.PRIVATE_WTOOLS_BOT_TOKEN }}
      PRIVATE_WTOOLS_BOT_SSH_KEY : ${{ secrets.PRIVATE_WTOOLS_BOT_SSH_KEY }}
      PRIVATE_WTOOLS_BOT_NPM_PASS : ${{ secrets.PRIVATE_WTOOLS_BOT_NPM_PASS }}
      PRIVATE_WTOOLS_BOT_EMAIL : ${{ secrets.PRIVATE_WTOOLS_BOT_EMAIL }}
      NODE_PRE_GYP_GITHUB_TOKEN : ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
        node-version : [ 14.x ]
    runs-on : ${{ matrix.os }}
    steps :
    - name : Setup git
      run : |
        git config --global core.autocrlf input
        git config --global user.email "testing@testing.com"
        git config --global user.name "Testing"
    - uses : actions/checkout@v2
      with :
        fetch-depth: 2
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - name : Save npm version
      id : getnpmver
      run : |
        echo "::set-output name=npmver::$(npm -v)"
    - name : Update npm if current version is 6
      if : "startsWith( steps.getnpmver.outputs.npmver, '6.' )"
      run : npm install -g npm@latest-6
    - run : npm -g i willbe@delta
    - run : will .npm.install
    - name : Environment
      run : env
    - run : npm list
      continue-on-error : true
    - if : startsWith( matrix.os, 'ubuntu' )
      run : xvfb-run --auto-servernum npm test
    - if : "!startsWith( matrix.os, 'ubuntu' )"
      run : npm test
